body:
  - type: markdown
    attributes:
      value: |
        Before asking a question, make sure it hasn't been already asked and answered. Check current issues, question.

        Also, be sure to check our [Knowledge Base](https://portal.portainer.io/knowledge) and [documentatio](https://documentation.portainer.io/) first.
        
        **DO NOT FILE DUPLICATE REQUESTS.**

  - type: textarea
    attributes:
      label: Ask a Question!
    validations:
      required: true