name: Bug Report
description: Create a report to help us improve.
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Welcome!
      description: |
        The issue tracker is for reporting bugs. For feature requests and other questions please use [discussions](https://github.com/samdulam/dashy/discussions)
        Link to community slack perhaps
        
        DO NOT FILE ISSUES FOR GENERAL SUPPORT QUESTIONS.
      options:
        - label: Yes, I've searched similar issues on [GitHub](https://github.com/portainer/poartainer/issues).
          required: true
        - label: Yes, I've checked [documentation](https://docs.portainer.io).
          required: true

  - type: textarea
    attributes:
      label: Problem Description?
      description: |
        How to write a good bug report?

        - Respect the issue template as much as possible.
        - The title should be short and descriptive.
        - Explain the conditions which led you to report this issue: the context.
        - The context should lead to something, an idea or a problem that you're facing.
        - Remain clear and concise.
        - Format your messages to help the reader focus on what matters and understand the structure of your message, use [Markdown syntax](https://help.github.com/articles/github-flavored-markdown)
      placeholder: A clear and concise description of what the bug is...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behaviour
      placeholder: A clear and concise description of what you expected to happen...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Behaviour?
      placeholder: A clear and concise description of what actually happens...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error   
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Portainer Edition?
      multiple: false
      options:
        - 'Business Edition (BE/EE)'
        - 'Community Edition (CE)'
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Portainer Version?
      multiple: false
      options:
        - '2.18.4'
        - '2.18.3'
        - '2.18.2'
        - '2.18.1'
        - '2.17.1'
        - '2.17.0'
        - '2.16.2'
    validations:
      required: true

  - type: input
    attributes:
      label: Portainer Version Input?
      description: |
        Enter a valid version (eg: 2.18.4)
        We only provide support for most recent version and previous 3
      placeholder: 2.18.4
    validations:
      required: true

  - type: input
    attributes:
      label: Platform and Version?
      description: |
        Enter a the container management platform (Docker | Swarm | Kubernetes along with version)
        Eg: Docker 24.0.3 | DOcker Swarm 24.0.3 | Kubernetes 1.26
      placeholder: Docker 24.0.3
    validations:
      required: true

  - type: input
    attributes:
      label: OS and Architecture?
      description: |
        Enter the Operating System, Version and Architecture 
        Eg: Ubuntu 22.04, amd64 | Rasbian arm64
      placeholder: Ubuntu 22.04, amd64
    validations:
      required: true

  - type: textarea
    attributes:
      label: Browser?
      description: Provide the browser and version details.
      placeholder: Chrome 114 | Edge 114
    validations:
      required: false

  - type: textarea
    attributes:
      label: Command used to deploy Portainer?
      description: Provide the command or compose used to deploy Portainer.
      placeholder: `docker run -p 9443:9443 portainer/portainer`
    validations:
      required: false