blank_issues_enabled: false
contact_links:
  - name: Getting Started with Portainer?
    url: https://documentation.portainer.io/quickstart/
    about: Checkout our quickstart guide..
  - name: Portainer Community Support
    url: https://community.portainer.io/about-the-community
    about: Have a question about Portainer CE? Find all the usual community channels here..
  - name: Portainer Business Support
    url: https://support.portainer.io/?login=1
    about: Have a question about Portainer Business? Contact our Support Specialist..
