blank_issues_enabled: false
contact_links:
  - name: Getting Started with Portainer?
    url: https://documentation.portainer.io/quickstart/
    about: Checkout our quickstart guide..
  - name: Portainer Community Support
    url: https://community.portainer.io/about-the-community
    about: Have a question about Portainer CE? Find all the usual community channels here..
  - name: Portainer Business
    url: https://www.portainer.io/portainerbusiness 
    about: Need enterprise grade support? Check out Portainer Business..
