name: "get-email"

on:
  workflow_dispatch:
    inputs:
      gh_username:
        description: 'username'
        required: true
        default: 'samdulam'
env:
  
jobs:
  Run-npm-on-Ubuntu:
    name: Run npm on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: |
          export GH_EMAIL_TOKEN=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
          sudo npm install --global github-email
          echo "email = $(github-email ${{ github.event.inputs.gh_username }})"
